# Generated by Django 3.1 on 2021-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='random code used for registration and for password reset', max_length=15)),
                ('used', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('R', 'registration'), ('PR', 'password reset')], default='R', max_length=2)),
            ],
        ),
    ]
