# Generated by Django 3.1 on 2021-03-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='action',
            field=models.CharField(choices=[('R', 'registration'), ('PR', 'password reset')], default='R', max_length=2),
        ),
    ]
