version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend:/frontend
      - ./nginx:/etc/nginx/conf.d
      - media-files:/media-files
      - static-files:/static-files
      - /etc/letsencrypt:/etc/letsencrypt

  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-15-february-2021/luna-group-project/capricorn/luna:latest
    restart: always
    env_file:
      - ./envs/dev.env
    command: 'sh /scripts/run.sh'
    volumes:
      - frontend:/frontend/build
      - media-files:/media-files
      - static-files:/static-files
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./envs/dev.env

volumes:
  postgres:
  media-files:
  static-files:
  frontend:
