name: luna

dependencies:
  - python=3.9
  - psycopg2=2.8
  - pip=21.0
  - pip:
      - Django==3.1
      - djangorestframework==3.12
      - djangorestframework-simplejwt==4.6
      - drf-yasg==1.20
      - Pillow==8.1
      - gunicorn==20.0
      - flake8==3.9
      - coreapi==2.3.3
      - Markdown==3.3
      - django-cors-headers==3.7
