# Generated by Django 3.1 on 2021-03-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0008_remove_restaurant_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('restaurants', models.ManyToManyField(blank=True, related_name='categories', to='restaurant.Restaurant')),
            ],
        ),
    ]
