# Generated by Django 3.1 on 2021-03-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210330_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='restaurants',
        ),
    ]
