# Generated by Django 3.1 on 2021-03-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0003_remove_restaurant_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ManyToManyField(choices=[('1', 'Vegetarian'), ('2', 'Vegan'), ('3', 'Fast Food'), ('4', 'All you can eat')], related_name='categories', to='restaurant.Restaurant')),
            ],
        ),
    ]
