# Generated by Django 3.1 on 2021-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_restaurant_category'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='restaurant',
            field=models.ManyToManyField(choices=[('1', 'Vegetarian'), ('2', 'Vegan'), ('3', 'Fast Food'), ('4', 'All you can eat'), ('5', 'Breakfast & Brunch')], related_name='categories', to='restaurant.Restaurant'),
        ),
    ]
