# Generated by Django 3.1 on 2021-04-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours_from',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours_to',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
