# Generated by Django 3.1 on 2021-03-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='WIFI',
            field=models.BooleanField(null=True, verbose_name='Internet test'),
        ),
    ]
