# Generated by Django 3.1 on 2021-04-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('restaurant', '0003_auto_20210401_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='WIFI',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(related_name='restaurants', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.CharField(max_length=70, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='credit_cards',
            field=models.BooleanField(blank=True, null=True, verbose_name='Credit cards'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_hours',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='take_away',
            field=models.BooleanField(blank=True, null=True, verbose_name='Take away'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='take_reservations',
            field=models.BooleanField(blank=True, null=True, verbose_name='Take reservations'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='waiter_service',
            field=models.BooleanField(blank=True, null=True, verbose_name='Waiter service'),
        ),
    ]
