# Generated by Django 3.1 on 2021-03-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_wifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='take_reservations',
            field=models.BooleanField(null=True, verbose_name='Take reservations'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='WIFI',
            field=models.BooleanField(null=True),
        ),
    ]
