# Generated by Django 3.1 on 2021-03-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210329_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='credit_cards',
            field=models.BooleanField(null=True, verbose_name='Credit cards'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='noise_level',
            field=models.CharField(choices=[('0', 'No information'), ('1', '$'), ('2', '$$'), ('3', '$$$')], default='0', max_length=2, verbose_name='Noise level'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='take_away',
            field=models.BooleanField(null=True, verbose_name='Take away'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='waiter_service',
            field=models.BooleanField(null=True, verbose_name='Waiter service'),
        ),
    ]
