# Generated by Django 3.1 on 2021-03-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20210329_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='noise_level',
            field=models.CharField(choices=[('0', 'No information'), ('1', '!'), ('2', '!!'), ('3', '!!!')], default='0', max_length=2, verbose_name='Noise level'),
        ),
    ]
