# Generated by Django 3.1 on 2021-03-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20210329_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
