# Generated by Django 3.1 on 2021-03-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20210329_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price_level',
            field=models.CharField(choices=[('0', 'No information'), ('1', '$'), ('2', '$$'), ('3', '$$$')], default='0', max_length=2, verbose_name='Price level'),
        ),
    ]
