# Generated by Django 3.1 on 2021-03-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20210330_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='categories',
        ),
    ]
