# Generated by Django 3.1 on 2021-03-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20210329_1621'),
        ('restaurant', '0007_restaurant_categories'),
    ]

    operations = [
    ]
