# Generated by Django 3.1 on 2021-03-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_restaurants'),
        ('restaurant', '0008_remove_restaurant_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='category.Category'),
        ),
    ]
