# Generated by Django 3.1 on 2021-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20210330_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='noise_level',
            field=models.CharField(blank=True, choices=[('0', 'No information'), ('1', '!'), ('2', '!!'), ('3', '!!!')], default='0', max_length=2, verbose_name='Noise level'),
        ),
    ]
