# Generated by Django 3.1 on 2021-03-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='things_i_love',
            new_name='things_i_like',
        ),
    ]
